{{- if .Values.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: speech-model-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.speech.hostModelPath }}
{{- end }}